from datetime import datetime
from src.models.event import Event


# ---------------------------------------------------------------------------
# Heuristic configuration
# ---------------------------------------------------------------------------

# Executables known to be Windows background services.
# Denylist approach: keep everything EXCEPT confirmed noise.
# Rationale: in forensics it is safer to over-include than to silently discard
# evidence, so we only exclude what we can confidently label as system activity.
NOISY_EXECUTABLES = frozenset({
    "svchost.exe",
    "runtimebroker.exe",
    "dllhost.exe",
    "taskhostw.exe",
    "conhost.exe",
    "audiodg.exe",
    "fontdrvhost.exe",
    "searchindexer.exe",
    "searchfilterhost.exe",
    "searchprotocolhost.exe",
    "wwahost.exe",
    "searchapp.exe",
    "applicationframehost.exe",
    "backgroundtaskhost.exe",
    "shellexperiencehost.exe",
    "startmenuexperiencehost.exe",
    "textinputhost.exe",
    "useroobebroker.exe",
    "lockapp.exe",
    "wmiprvse.exe",
    "rundll32.exe",
    "tiworker.exe",
    "trustedinstaller.exe",
    "compattelrunner.exe",
    "mpcmdrun.exe",
})

# Path fragments that indicate Windows system directories.
# MFT events under these paths are almost always background activity.
EXCLUDED_MFT_PATHS = frozenset({
    "windows",
    "program files",
    "program files (x86)",
    "programdata",
    "$recycle.bin",
    "system volume information",
})

# Path fragments that strongly suggest direct user activity.
USER_MFT_PATHS = frozenset({
    "desktop",
    "documents",
    "downloads",
})

# File extensions associated with user-created or user-opened content.
RELEVANT_EXTENSIONS = frozenset({
    ".txt", ".doc", ".docx", ".pdf",
    ".jpg", ".png",
    ".py", ".cpp", ".java",
    ".bat", ".ps1", ".lnk",
})

# File extensions associated with system/runtime files — rarely forensically
# meaningful and very common, so they create a lot of noise in MFT events.
EXCLUDED_EXTENSIONS = frozenset({
    ".dll", ".sys", ".tmp", ".log",
    ".mui", ".dat", ".cache", ".etl",
})

# URL prefixes that indicate browser-internal pages rather than user navigation.
# These are generated by the browser itself (settings, new tab, extension pages)
# and carry no investigative value about the user's online activity.
INTERNAL_URL_PREFIXES = (
    "chrome://",
    "edge://",
    "about:",
    "chrome-extension://",
    "moz-extension://",
)


# ---------------------------------------------------------------------------
# Source-specific heuristics
# ---------------------------------------------------------------------------

def _is_relevant_prefetch(event: Event) -> bool:
    """Return False if the executable is a known background process.

    The executable name is read from raw_data["executable"] when available,
    falling back to the description field for forward compatibility.
    """
    executable = event.raw_data.get("executable", event.description).lower()
    # Strip any leading path component — we only care about the filename.
    executable = executable.rsplit("\\", 1)[-1].rsplit("/", 1)[-1]
    return executable not in NOISY_EXECUTABLES


def _is_relevant_mft(event: Event) -> bool:
    """Return True if the MFT event is likely related to user activity.

    MFT events are the noisiest source — every file system operation is
    recorded, including background indexing, temp file churn, and OS updates.
    A strict multi-step filter is therefore appropriate here:

      1. Reject events from known system paths.
      2. Reject events with extensions that indicate runtime/system files.
      3. Accept events in known user folders (Desktop, Documents, Downloads).
      4. Accept events with extensions associated with user-created content.
      5. Reject everything else — the default for MFT is exclusion, not inclusion.
    """
    file_path = event.raw_data.get("file_path", event.description).lower()

    # Extract extension from the filename only, not the full path.
    # Using the full path with rsplit would give wrong results when a parent
    # directory name contains a dot (e.g. C:\user.name\docs\report.pdf).
    filename = file_path.rsplit("\\", 1)[-1].rsplit("/", 1)[-1]
    extension = ("." + filename.rsplit(".", 1)[-1]) if "." in filename else ""

    # Step 1: reject system paths
    if any(fragment in file_path for fragment in EXCLUDED_MFT_PATHS):
        return False

    # Step 2: reject by extension
    if extension in EXCLUDED_EXTENSIONS:
        return False

    # Step 3 & 4: accept if user path or relevant extension
    in_user_path = any(fragment in file_path for fragment in USER_MFT_PATHS)
    has_relevant_ext = extension in RELEVANT_EXTENSIONS

    return in_user_path or has_relevant_ext


def _is_relevant_browser(event: Event) -> bool:
    """Return False for browser-internal URLs that do not reflect user navigation.

    Pages like chrome://settings or about:blank are generated by the browser
    itself, not by user intent. They do not represent meaningful online activity
    and would only add noise to the timeline.
    All other URLs are kept — browser history is almost always user-relevant.
    """
    url = event.raw_data.get("url", "").lower()
    if any(url.startswith(prefix) for prefix in INTERNAL_URL_PREFIXES):
        return False
    return True


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def is_relevant_event(event: Event) -> bool:
    """Apply source-specific heuristics to decide if an event is worth keeping.

    Events from unknown or unlisted sources pass through unfiltered —
    we only discard what we can confidently identify as noise.
    """
    if event.source == "prefetch":
        return _is_relevant_prefetch(event)
    if event.source == "mft":
        return _is_relevant_mft(event)
    if event.source == "browser":
        return _is_relevant_browser(event)
    # Unknown source: keep by default — better to include than miss evidence.
    return True


def filter_by_time_range(
    events: list[Event],
    start: datetime | None = None,
    end: datetime | None = None,
) -> list[Event]:
    """Return only events within the optional [start, end] time range.

    Both bounds are inclusive. A None bound means that side is open-ended.
    """
    result = events
    if start is not None:
        result = [e for e in result if e.timestamp >= start]
    if end is not None:
        result = [e for e in result if e.timestamp <= end]
    return result


def filter_by_sources(events: list[Event], sources: list[str]) -> list[Event]:
    """Return only events whose source matches one of the given source names."""
    allowed = set(sources)
    return [e for e in events if e.source in allowed]


def _config_value(config: dict | None, *keys: str):
    if not config:
        return None
    for key in keys:
        if key in config and config[key] not in (None, "", []):
            return config[key]
    return None


def _event_path(event: Event) -> str:
    return (
        event.raw_data.get("file_path")
        or event.raw_data.get("local_path")
        or event.raw_data.get("process_path")
        or event.raw_data.get("url")
        or ""
    )


def _event_extension(event: Event) -> str:
    ext = event.raw_data.get("extension", "")
    if ext:
        return ext.lower() if ext.startswith(".") else f".{ext.lower()}"
    path = _event_path(event).lower()
    filename = path.rsplit("\\", 1)[-1].rsplit("/", 1)[-1]
    if "." in filename:
        return "." + filename.rsplit(".", 1)[-1]
    return ""


def _event_process(event: Event) -> str:
    value = (
        event.raw_data.get("process_name")
        or event.raw_data.get("executable")
        or event.application
        or ""
    )
    return value.rsplit("\\", 1)[-1].rsplit("/", 1)[-1].lower()


def _filter_by_include_paths(events: list[Event], include_paths: list[str] | tuple[str, ...]) -> list[Event]:
    needles = [p.lower().replace("/", "\\") for p in include_paths]
    result = []
    for event in events:
        path = (
            event.raw_data.get("file_path")
            or event.raw_data.get("local_path")
            or ""
        )
        if not path:
            result.append(event)
            continue
        normalised = path.lower().replace("/", "\\")
        if any(n in normalised for n in needles):
            result.append(event)
    return result


def _filter_by_extensions(events: list[Event], extensions: list[str] | tuple[str, ...]) -> list[Event]:
    allowed = {ext.lower() if ext.startswith(".") else f".{ext.lower()}" for ext in extensions}
    return [e for e in events if _event_extension(e) in allowed]


def _filter_by_excluded_processes(events: list[Event], processes: list[str] | tuple[str, ...]) -> list[Event]:
    excluded = {p.lower() for p in processes}
    return [e for e in events if _event_process(e) not in excluded]


def filter_events(
    events: list[Event],
    config: dict | None = None,
    sources: list[str] | None = None,
    start: datetime | None = None,
    end: datetime | None = None,
) -> list[Event]:
    """Apply all active filters to a list of events and return the result.

    Filtering order:
      1. Source whitelist  — if --sources was specified, drop all other sources.
      2. Time range        — if --start or --end was specified, drop out-of-range events.
      3. Relevance         — source-specific heuristics, always applied.

    The original list is not modified.
    """
    result = events

    sources = sources or _config_value(config, "sources", "include_sources")
    start = start or _config_value(config, "start", "analysis_start")
    end = end or _config_value(config, "end", "analysis_end")

    if sources:
        result = filter_by_sources(result, sources)

    result = filter_by_time_range(result, start=start, end=end)

    result = [e for e in result if is_relevant_event(e)]

    include_paths = _config_value(config, "include_paths")
    if include_paths:
        result = _filter_by_include_paths(result, include_paths)

    include_extensions = _config_value(config, "include_extensions")
    if include_extensions:
        result = _filter_by_extensions(result, include_extensions)

    exclude_processes = _config_value(config, "exclude_processes")
    if exclude_processes:
        result = _filter_by_excluded_processes(result, exclude_processes)

    return result
